apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: acx-service
  namespace: argocd
spec:
  project: default
  source:
   repoURL: https://github.com/shafibytes/test.git
   path: helm/onboarding
   targetRevision: HEAD
   helm:
      releaseName: acx-service-onboard
      valueFiles:
      - values-acx-service.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: acx-services

  syncPolicy:
    automated:
      selfHeal: true
      prune: true