apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: acx-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/shafibytes/test.git
    path: helm/onboarding
    targetRevision: HEAD
    helm:
      releaseName: acx-service-onboard
      valuesObject:
        rbac:
          role: 
           createRoles: true
           name: acx-service

          serviceAccount:
            Name: acx-service
            iamRole: arn:aws:1231241:role/acx-service-read

          Namespace:
            Name: acx-service
            linkerdInject: false
  destination:
    server: "https://kubernetes.default.svc"
    namespace: acx-services

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true