{{- if .Values.rbac.role.createRoles -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.rbac.role.name }}-readonly
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list","create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.rbac.role.name }}-deployment
rules:
- apiGroups: [""]
  resources: ["deployments"]
  verbs: ["get", "list", "create", "delete"]
{{- end }}
