apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: false
metadata:
  name: {{ .Values.rbac.serviceAccount.Name }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.rbac.serviceAccount.iamRole }}
